name: Transition Jira Ticket

on:
  pull_request:
    types: [opened]

jobs:
  transition-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira Issue ID from Branch Name
        id: extract-issue-id
        run: |
          # Assuming branch name contains the Jira issue key in the format PROJECT-123
          ISSUE_KEY=$(echo "${{ github.head_ref }}" | grep -oE '[A-Z]+-[0-9]+')
          echo "issue_key=$ISSUE_KEY" >> $GITHUB_ENV

      - name: Transition Jira Ticket to "Done"
        if: env.issue_key != ''
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
          ISSUE_KEY: ${{ env.issue_key }}
        run: |
          curl -u "$JIRA_USER:$JIRA_API_TOKEN" \
          -X POST \
          -H "Content-Type: application/json" \
          --data '{"transition": {"id": "51"}}' \  # Replace 51 with the actual ID for "Done"
          "$JIRA_URL/rest/api/2/issue/$ISSUE_KEY/transitions"
