name: Transition Jira Ticket

on:
  pull_request:
    types: [opened]

jobs:
  transition-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Transition Jira Ticket CG-1 to "Done"
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
        run: |
          curl -u "$JIRA_USER:$JIRA_API_TOKEN" \
          -X POST \
          -H "Content-Type: application/json" \
          --data '{"transition": {"id": "51"}}' \
          "$JIRA_URL/rest/api/2/issue/CG-1/transitions"
